version: '2'
services:
    mysql:
        build: mysql
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        volumes:
          - ./mysql/data:/docker-entrypoint-initdb.d
        networks:
          - backend
    php:
        build: php-fpm
        container_name: php-fpm
        restart: always
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        depends_on:
          - mysql
#        command: ["sh", "./docker/php-fpm/database-connect.sh"]
        networks:
          - backend
    nginx:
        build: nginx
        container_name: nginx
        restart: always
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached 
        networks:
          - backend
#
networks:
  backend :
