<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Unit extends \App\Entity\Unit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'ref', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'areas', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'section', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'resps'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'ref', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'areas', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'section', '' . "\0" . 'App\\Entity\\Unit' . "\0" . 'resps'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Unit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRef(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRef', []);

        return parent::getRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setRef(string $ref): \App\Entity\Unit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRef', [$ref]);

        return parent::setRef($ref);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Unit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreas', []);

        return parent::getAreas();
    }

    /**
     * {@inheritDoc}
     */
    public function addAreas(\App\Entity\Area $areas): \App\Entity\Unit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAreas', [$areas]);

        return parent::addAreas($areas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAreas(\App\Entity\Area $areas): \App\Entity\Unit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAreas', [$areas]);

        return parent::removeAreas($areas);
    }

    /**
     * {@inheritDoc}
     */
    public function getSection(): ?\App\Entity\Section
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSection', []);

        return parent::getSection();
    }

    /**
     * {@inheritDoc}
     */
    public function getSectionData(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectionData', []);

        return parent::getSectionData();
    }

    /**
     * {@inheritDoc}
     */
    public function getSectionId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectionId', []);

        return parent::getSectionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSection(?\App\Entity\Section $section): \App\Entity\Unit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSection', [$section]);

        return parent::setSection($section);
    }

    /**
     * {@inheritDoc}
     */
    public function getResps(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResps', []);

        return parent::getResps();
    }

    /**
     * {@inheritDoc}
     */
    public function addResp(\App\Entity\Resp $resp): \App\Entity\Unit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addResp', [$resp]);

        return parent::addResp($resp);
    }

    /**
     * {@inheritDoc}
     */
    public function removeResp(\App\Entity\Resp $resp): \App\Entity\Unit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeResp', [$resp]);

        return parent::removeResp($resp);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
