<?php

namespace ContainerHHrGXPM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OomRAMXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oomRAMX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oomRAMX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'logger' => ['privates', 'logger', 'getLoggerService', false],
        ], [
            'doctrine' => '?',
            'fileUploader' => 'App\\Service\\FileUploader',
            'logger' => '?',
        ]);
    }
}
