<?php

namespace ContainerHHrGXPM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidateActionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ValidateActionController' shared autowired service.
     *
     * @return \App\Controller\ValidateActionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ValidateActionController.php';

        $container->services['App\\Controller\\ValidateActionController'] = $instance = new \App\Controller\ValidateActionController();

        $instance->setContainer(($container->privates['.service_locator.BE5.yuK'] ?? $container->load('get_ServiceLocator_BE5_YuKService'))->withContext('App\\Controller\\ValidateActionController', $container));

        return $instance;
    }
}
