FROM mysql:8.0.17
ENV MYSQL_ROOT_PASSWORD docb_psw
ENV MYSQL_USER docb_user
ENV MYSQL_PASSWORD docb_psw
ENV MYSQL_DATABASE testdb

mysql_config_editor set --login-path=local --host=localhost --user=root --password
