<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZL3ikJv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZL3ikJv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZL3ikJv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZL3ikJv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZL3ikJv\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZL3ikJv',
    'container.build_id' => 'b6db9739',
    'container.build_time' => 1646652945,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZL3ikJv');
